### ISSUE TITLE
Simulation in Casino2 fails with current pyMonteCarlo version

### ISSUE THREAD

**Issue by 0b11001111** [pymontecarlo/pymontecarlo#50]
Trying to run the following code snippet results in the attached error. I don't know if that's caused by incomplete options, a bug in the current version of pyMonteCarlo or a not detected Casion2 instance. My guess is the last one since I was not able to follow the installation guide (https://github.com/pymontecarlo/pymontecarlo/wiki/Simple-example) one to one. 

``` python
#!/usr/bin/env python3
"""
example script for demonstrating usage of pyMonteCarlo
"""

# Standard library modules.
import math
import sys

# Local modules
from pymontecarlo.options.analysis.kratio import KRatioAnalysis
from pymontecarlo.options.beam.gaussian import GaussianBeamBuilder
from pymontecarlo.options.detector import PhotonDetector
from pymontecarlo.options.material import Material
from pymontecarlo.options.options import OptionsBuilder
from pymontecarlo.options.sample import VerticalLayerSample
from pymontecarlo.options.sample.base import Layer
from pymontecarlo.project import Project
from pymontecarlo.runner.local import LocalSimulationRunner
from pymontecarlo_casino2.program import Casino2ProgramBuilder


def generate_options_1():
    """
    # Photonenintensität vs. Energie (3keV-15keV, 2keV-Schritte)
    # reines Substrat (Si, Fe)
    """
    program_bilder = Casino2ProgramBuilder()
    program_bilder.add_number_trajectories(100)

    programs = program_bilder.build()
    sample = VerticalLayerSample(left_material=Material.pure(14),
                                 right_material=Material.pure(14),
                                 layers=[Layer(Material.pure(26), 200e-9)])

    photon_detector = PhotonDetector('myDetector', math.radians(35.0))

    analysis = KRatioAnalysis(photon_detector)

    beam_builder = GaussianBeamBuilder()
    beam_builder.add_energy_eV(15e3)
    beam_builder.add_diameter_m(10e-9)
    beam_builder.add_linescan_x(-1000e-9, 1001e-9, 100e-9)

    beams = beam_builder.build()

    options_builder = OptionsBuilder()
    options_builder.add_sample(sample)
    options_builder.add_analysis(analysis)
    for program in programs:
        options_builder.add_program(program)
    for beam in beams:
        options_builder.add_beam(beam)

    options = options_builder.build()

    return options


def simulate(project, options):
    with LocalSimulationRunner(project, max_workers=3) as runner:

        futures = runner.submit(*options)

        print('{} simulations launched'.format(len(futures)))

        while not runner.wait(1):
            print(runner.progress)

            print('{} simulations succeeded'.format(runner.done_count))
            print('{} simulations failed'.format(runner.failed_count))
            for future in runner.failed_futures:
                print(future.exception())


def main(argv=None):
    options = generate_options_1()

    project = Project()

    simulate(project, options)

    project.recalculate()

    # odf = project.create_options_dataframe()
    # rdf = project.create_results_dataframe()

    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))

```

error log
[log.txt](https://github.com/pymontecarlo/pymontecarlo/files/1466452/log.txt)

packages installed in virtual environment
[pip.txt](https://github.com/pymontecarlo/pymontecarlo/files/1466453/pip.txt)

**Comment by ppinard** [comment]
Can you add this at the beginning of your script and send me the log:

```python
import logging
logging.basicConfig()
logging.getLogger().setLevel(logging.DEBUG)
```

The script works on my PC, except that the `recalculate` takes a very long time. Something I need to check.

**Comment by 0b11001111** [comment]
done

[log.txt](https://github.com/pymontecarlo/pymontecarlo/files/1469075/log.txt)

**Comment by ppinard** [comment]
It seems there is a problem with the export to Casino2 .sim file. Can you try this simpler script:

```python
#!/usr/bin/env python3

import math

from pymontecarlo.options.analysis.kratio import KRatioAnalysis
from pymontecarlo.options.beam.gaussian import GaussianBeam
from pymontecarlo.options.detector import PhotonDetector
from pymontecarlo.options.material import Material
from pymontecarlo.options.options import Options
from pymontecarlo.options.sample import SubstrateSample
from pymontecarlo.project import Project
from pymontecarlo.runner.local import LocalSimulationRunner
from pymontecarlo_casino2.program import Casino2Program


program = Casino2Program()
program.number_trajectories = 100

sample = SubstrateSample(Material.pure(14))

photon_detector = PhotonDetector('myDetector', math.radians(35.0))
analysis = KRatioAnalysis(photon_detector)

beam = GaussianBeam(15e3, 10e-9)

options = Options(program, beam, sample, [analysis])

exporter = program.create_exporter()
exporter.export(options, '.')
```

It should create an `options.sim` in the folder where the script resides.

**Comment by 0b11001111** [comment]
I'm on the latest version of all modules and again it crashes. It seems like `SimulationOptions` are not properly created in `pymontecarlo_casino2.exporter.Casino2Exporter._export` and the following error is risen in `pymontecarlo_casino2.exporter.Casino2Exporter._export_program`:

```
Traceback (most recent call last):
  File "~/Workspace/pyMonteCarlo/scripts/simulation.py", line 130, in <module>
    exporter.export(options, '.')
  File "~/Workspace/pyMonteCarlo/pymontecarlo/pymontecarlo/options/program/exporter.py", line 35, in export
    self._export(options, dirpath, errors)
  File "~/Workspace/pyMonteCarlo/pymontecarlo-casino2/pymontecarlo_casino2/exporter.py", line 107, in _export
    self._run_exporters(options, errors, simdata, simops)
  File "~/Workspace/pyMonteCarlo/pymontecarlo/pymontecarlo/options/program/exporter.py", line 57, in _run_exporters
    self._export_program(options.program, options, errors, *args, **kwargs)
  File "~/Workspace/pyMonteCarlo/pymontecarlo-casino2/pymontecarlo_casino2/exporter.py", line 153, in _export_program
    simops.setNumberElectrons(program.number_trajectories)
AttributeError: 'NoneType' object has no attribute 'setNumberElectrons'
```

Log file:
[error.txt](https://github.com/pymontecarlo/pymontecarlo/files/1491260/error.txt)

**Comment by ppinard** [comment]
Can you check the md5 sum of pymontecarlo_casino2/templates/Substrate.sim? I got `fdb922d90bc469000370ac7e2745c11e`. It looks like the template cannot be read.

**Comment by 0b11001111** [comment]
My checksum differs.

```
...:~/Workspace/pyMonteCarlo/pymontecarlo-casino2/pymontecarlo_casino2/templates$ md5sum *.sim 
1ca398b250a3c929ab5b500c87e2801a  HorizontalLayers10.sim
52f02d54d8ec1cc148292bccc206858a  HorizontalLayers11.sim
5b2ac7f8d0214b54ec827d29870d7817  HorizontalLayers2.sim
2f975abb9e19eeb66c352ef83eca7644  HorizontalLayers3.sim
cba35d95a7af67f69c665b7dd81a05f7  HorizontalLayers4.sim
acc33e1fa3f6a082effaf88ca8be3fc7  HorizontalLayers5.sim
6048c5b05cb576c2043eaca9ab0448f3  HorizontalLayers6.sim
2e78c2687922e018aa1586ec5c3a2305  HorizontalLayers7.sim
4f148e953ee925c36d27f442b5df8665  HorizontalLayers8.sim
b79e7d6152fa732616c4ae06a46ece14  HorizontalLayers9.sim
e5b789935a8974c2ff02325ac6bc2872  Substrate.sim
d6416bbedcb842de12e522ce471185f9  VerticalLayers10.sim
2088be0bf45a4043deefab88886306e7  VerticalLayers11.sim
3887eb0ceacee92c0aa2867ea016957b  VerticalLayers2.sim
f55bb076e77694aba019adbc0549c890  VerticalLayers3.sim
d72d68901285cef1e8c795e39290633a  VerticalLayers4.sim
a2db412007c66b2e64c1b66090ccc4d2  VerticalLayers5.sim
f65a7379d24f30f85b0ef3c766c5b00c  VerticalLayers6.sim
d963a56f1fee22cf45029d9badc90f82  VerticalLayers7.sim
034836ee020cfd5908a13b3f5cb75a62  VerticalLayers8.sim
084aaed4a42335355bbd5889930328c1  VerticalLayers9.sim
```

**Comment by ppinard** [comment]
I am a bit puzzled. I download `Substrate.sim` directly from GitHub and the md5sum matches mine. Do you have [Git LFS](https://git-lfs.github.com) installed?

**Comment by 0b11001111** [comment]
No, _Git LFS_ was not installed. I removed the `pymontecarlo-casino2` package, installed _Git LFS_ and reinstalled `pymontecarlo-casino2`. Now the checksums match and the scripts terminates without an error. 
I'll close this issue once I tested the original script.

**Comment by ppinard** [comment]
I added a warning in the [installation documentation](http://pymontecarlo.readthedocs.io/en/master/installation.html) about Git LFS.

I also made some speed improvements in *pymontecarlo* and *pyxray*. I would suggest you upgrade both before testing the original script.

**Comment by 0b11001111** [comment]
The changes in pyxray cause some trouble. When I run the script from the initial question I got following error:

```
Traceback (most recent call last):
  File "~/Workspace/pyMonteCarlo/scripts/simulation.py", line 101, in <module>
    sys.exit(main(sys.argv))
  File "~/Workspace/pyMonteCarlo/scripts/simulation.py", line 89, in main
    project.recalculate()
  File "~/Workspace/pyMonteCarlo/pymontecarlo/pymontecarlo/project.py", line 63, in recalculate
    analysis.calculate(simulation, tuple(self.simulations))
  File "~/Workspace/pyMonteCarlo/pymontecarlo/pymontecarlo/options/analysis/photonintensity.py", line 38, in calculate
    xrayline = pyxray.xray_line(z, transitionset)
AttributeError: module 'pyxray' has no attribute 'xray_line'
```

Log file
[log.txt](https://github.com/pymontecarlo/pymontecarlo/files/1511736/log.txt)

**Comment by ppinard** [comment]
It looks like you do not have the latest version of *pyxray* (1.3.3).

**Comment by 0b11001111** [comment]
The code was up to date already. Rebuilding the database fixed that issue.
