### ISSUE TITLE
deep copy of 'Options' instance

### ISSUE THREAD

**Issue by 0b11001111** [pymontecarlo/pymontecarlo#58]
I'm trying to create a deep copy of an instance of *Options* to allow another class to modify it without affecting the original. I used `copy.deepcopy` as in the following sample:

```Python3
import math
from copy import deepcopy

from pymontecarlo.options.analysis.kratio import KRatioAnalysis
from pymontecarlo.options.beam.gaussian import GaussianBeam
from pymontecarlo.options.detector import PhotonDetector
from pymontecarlo.options.material import Material
from pymontecarlo.options.options import Options
from pymontecarlo.options.sample import VerticalLayerSample
from pymontecarlo.options.sample.base import Layer
from pymontecarlo_casino2.program import Casino2Program

program = Casino2Program(number_trajectories=10000)
photon_detector = PhotonDetector('myPhotonDetector', math.radians(40.), math.radians(0.))
analysis = KRatioAnalysis(photon_detector)
beam = GaussianBeam(energy_eV=15e3, diameter_m=0.)
sample = VerticalLayerSample(left_material=Material.pure(26),
                             right_material=Material.pure(26),
                             layers=[Layer(Material('MnAl', {25: 0.9, 13: 0.1}), 10e-9)])

base_options = Options(program, beam, sample, [analysis])

working_copy = deepcopy(base_options)

```
but it fails with error:

```
Traceback (most recent call last):
  File "~/workspace/Python/pyMonteCarlo/reconstruction/script.py", line 99, in <module>
    sys.exit(main(sys.argv))
  File "~/workspace/Python/pyMonteCarlo/reconstruction/script.py", line 46, in main
    base_options_copy = deepcopy(base_options)
  File "~/workspace/Python/venvs/pyMonteCarlo/lib64/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "~/workspace/Python/venvs/pyMonteCarlo/lib64/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "~/workspace/Python/venvs/pyMonteCarlo/lib64/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "~/workspace/Python/venvs/pyMonteCarlo/lib64/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "~/workspace/Python/venvs/pyMonteCarlo/lib64/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "~/workspace/Python/venvs/pyMonteCarlo/lib64/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "~/workspace/Python/venvs/pyMonteCarlo/lib64/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "~/workspace/Python/venvs/pyMonteCarlo/lib64/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "~/workspace/Python/venvs/pyMonteCarlo/lib64/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
  File "~/workspace/Python/venvs/pyMonteCarlo/lib64/python3.6/enum.py", line 46, in _break_on_call_reduce
    raise TypeError('%r cannot be pickled' % self)
TypeError: <ElasticCrossSectionModel.MOTT_CZYZEWSKI1990: ('Mott by interpolation (Czyzewski)', 'Czyzewski (1990)')> cannot be pickled
```

Is it a good idea to copy options at all or is there good reason not to do that?

**Comment by ppinard** [comment]
The problem was related to the Enum used for the models. The last commit should contain a fix for this. I also added a test in `test_options` to make sure `copy.deepcopy` works.

**Comment by 0b11001111** [comment]
Now it works, thank you!
