### ISSUE TITLE
AttributeError on a fresh install of pyMonteCarlo

### ISSUE THREAD

**Issue by hasni4** [pymontecarlo/pymontecarlo#75]
Hi,

So I've done a fresh install of pyMonteCarlo following the instructions on https://pymontecarlo.readthedocs.io/en/latest/installation.html as a Python Package. 
This downloaded pymontecarlo-casino2-1.0.1, pymontecarlo-1.0.0 and pyxray-1.7.0. I'm running Python 3.8.5 from anaconda3 on a Windows device. When following the tutorial on how to run a simulation through python scripts, I get an AttributeError from the line: 
from pymontecarlo_casino2.program import Casino2Program

The full error message is:
`Traceback (most recent call last):

  File "C:\Users\hasni\.spyder-py3\testing-pymontecarlo.py", line 8, in <module>
    from pymontecarlo_casino2.program import Casino2Program

  File "C:\Users\hasni\anaconda3\lib\site-packages\pymontecarlo_casino2\program.py", line 16, in <module>
    from pymontecarlo_casino2.exporter import Casino2Exporter

  File "C:\Users\hasni\anaconda3\lib\site-packages\pymontecarlo_casino2\exporter.py", line 31, in <module>
    from pymontecarlo.options.analysis import PhotonIntensityAnalysis, KRatioAnalysis

  File "C:\Users\hasni\anaconda3\lib\site-packages\pymontecarlo\options\analysis\__init__.py", line 5, in <module>
    from pymontecarlo.options.analysis.kratio import KRatioAnalysis

  File "C:\Users\hasni\anaconda3\lib\site-packages\pymontecarlo\options\analysis\kratio.py", line 14, in <module>
    from pymontecarlo.options.analysis.photon import PhotonAnalysis, PhotonAnalysisBuilder

  File "C:\Users\hasni\anaconda3\lib\site-packages\pymontecarlo\options\analysis\photon.py", line 16, in <module>
    [pyxray.xray_transitionset('K'),

AttributeError: module 'pyxray' has no attribute 'xray_transitionset

What should I do from here?

`

**Comment by ppinard** [comment]
Thank you for the issue. I made changes to pyxray but didn't have the time to create a new pymontecarlo release. While I try to fix the issue, here are two interim solutions:

1. Use pymontecarlo source (preferred). Clone the latest *pymontecarlo* and *pymontecarlo-casino2* repositories and follow the "development" installation [instructions](https://pymontecarlo.readthedocs.io/en/latest/installation.html#development).
2. Uninstall pyxray 1.7.0 and install version 1.5.0

**Comment by hasni4** [comment]
Hi,

I've followed the instructions for the development installation (made sure to download Git LF5) and downloaded pyxray version 1.5.0. Now when running the nosetests I get a 4 errors and 1 failure. I'm not the best with seeing what is wrong as I am sort of new to doing this type of thing but it says ERROR: Failure: NotFound (No X-ray transition found) 4 times and then FAIL: test__main__.test__main__. 

If you could guide me to what other information you need to see what is going wrong, hopefully we can get to the bottom of this.

**Comment by drix00** [comment]
I think you mix the 2 solution together. Either do solution 1, with  version 1.7.0 of pyxray. 

OR solution 2 with version pymontecarlo-1.0.0, install version 1.5.0 of pyxray: 
`pip install -U "pyxray=1.5.0"`

**Comment by hasni4** [comment]
Thanks for the clearification. I tried solution 1 with pyxray 1.7.0 and reran the nosetests. I now get 22 errors and I've attached it so you can view it. However, when downloading pymontecarlo-casino2 and running the nosetests for that I got no errors and I could run the the tutorial to set up sample (https://pymontecarlo.readthedocs.io/en/latest/tutorial-python.html) as well. 

[nosetests.txt](https://github.com/pymontecarlo/pymontecarlo/files/5985925/nosetests.txt)

**Comment by hasni4** [comment]
Hi,

Just to follow up on this, I tried running a simulation based on the a sample I set up (a gold carbon vertical grain boundary) and the used come of the code to run the simulation from the example given in the docs folder (https://github.com/pymontecarlo/pymontecarlo/blob/master/docs/examples/example_13062017.py). IThe code is:

```
import os
import tempfile
import sys
import math
import matplotlib.pyplot as plt
from pymontecarlo_casino2.program import Casino2Program
from pymontecarlo.options.beam.gaussian import GaussianBeam, GaussianBeamBuilder
from pymontecarlo.options.material import Material
from pymontecarlo.options.sample import VerticalLayerSample
from pymontecarlo.figures.sample import SampleFigure, Perspective
from pymontecarlo.options.detector.photon import PhotonDetector
from pymontecarlo.options.analysis.photonintensity import PhotonIntensityAnalysis
from pymontecarlo.options.options import OptionsBuilder
from pymontecarlo.runner.helper import run_async
from pymontecarlo.runner.local import LocalSimulationRunner
from pymontecarlo.project import Project
from pymontecarlo.results.photonintensity import (
    EmittedPhotonIntensityResultBuilder,
    EmittedPhotonIntensityResult,
)
def main(argv=None):    
    #PROGRAM
    program = Casino2Program(5000)          #number of trajectories 
    #program.number_trajectories = 6000     Change number of trajectories
    
    #BEAM
    beam = GaussianBeam(15e3, 10e-9)        #beam energy and diameter
    
    #beam.x_m = 11e-9                       Default is 0,0 use this to change 
    #beam.y_m = 100e-9                      position of beam
    
    
    builder = GaussianBeamBuilder()         #LINESCAN BUILDER
    builder.add_energy_keV(15)
    builder.add_diameter_m(10e-9)
    builder.add_linescan_x(-40e-9, 40e-9, 20e-9)
    beams = builder.build()
    
    
    #SAMPLE
    """
    Therea are 5 different samples:
        substrate using SubstrateSample
        inclusion using InclusionSample 
        horizontal layered using HorizontalLayerSample 
        vertical layered using VericalLayerSample
        sphere using SphereSample
    """
    carbon = Material.pure(6)             #Pure carbon
    gold = Material.pure(79)
    """
    SiO2 = Material.from_formula('Si02')   #From formula
    
    composition = {29: 0.4, 30:0.6}
    brass = Material('Brass', composition)  #From composition 
    """
    #material.density_kg_per_m3 = 1000      change mass density
    #material.density_g_per_cm3 = 2.66 
    
    sample = VerticalLayerSample(left_material=carbon, right_material=gold) #making a sample with 3 layers
    """
    sample.add_layer(SiO2, 100e-9)
    sample.add_layer(brass, 50e-9)
    """
    plt.figure()
    plt.subplot("111")
    samplefig = SampleFigure(sample)
    samplefig.perspective = Perspective.XZ
    samplefig.draw(plt.gca())
    plt.show()
    
    #SETTING UP DETECTOR AND ANALYSIS
    detector = PhotonDetector(name='detector_1', elevation_rad = math.radians(40))
    photon_analysis = PhotonIntensityAnalysis(detector)
    
    #SETTING UP OPTIONS
    OB = OptionsBuilder()
    OB.programs = [program]
    OB.beams = beams
    OB.sanples = [sample]
    OB.analysis = [photon_analysis]
    options = OB.build()
    
    #RUNNING SIMULATION
    project = Project()
    
    with LocalSimulationRunner(project) as runner:
        futures = runner.submit(*options)
        
        print("{} simulations launched".format(len(futures)))
        
        while not runner.wait(1):
            print(runner.progress)
        
            print("{} simulations succeeded".format(runner.done_count))
            print("{} simulations failed".format(runner.failed_count))
            for future in runner.failed_futures:
                print(future.exception())
                
    project.recalculate()
    print("{} were simulated".format(len(project.simulations)))
    
    #GETTING RESULTS
    data_all = []
    
    for simulation in project.simulations:
        # results = simulation.results
        position = simulation.options.beam.x0_m
    
        for unkresult in simulation.find_result(EmittedPhotonIntensityResult):
    
            for xrayline, unkintensity in unkresult.items():
                # z = xrayline.atomic_number
                data = unkintensity.nominal_value
                data_all.append((xrayline, position, data))
    
    results = {}
    
    for x, p, d in data_all:
        if not x in results:
            results[x] = []
        results[x].append((p, d))
        
    sorted_results = []
    for k, v in results.items():
        v.sort(key=lambda t: t[0])
        print("{}\t{}".format(k, v))
        print(v)
        plot_results(k, v)
        sorted_results.append((k, v))
    return(sorted_results)
    print(sorted_results)

def plot_results(label, listoftuples):
    # ylabels = {'kratio': 'k-ratio', 'mass': 'Mass (%)', 'atom': 'Atom (%)'}

    fig = plt.figure()
    ax = fig.add_subplot("111")

    ax.set_xlabel("Distance (nm)")
    ax.set_ylabel("Intensity")
    plt.plot((*zip(*listoftuples)), label=label)
    plt.legend()
    plt.show()
    print(label)
    
if __name__ == "__main__":
    sys.exit(main(sys.argv))
```

I get the error: 
Traceback (most recent call last):

  File "C:\Users\hasni\pymontecarlo\pymontecarlo-casino2\testing-pymontecarlo.py", line 154, in <module>
    sys.exit(main(sys.argv))

  File "C:\Users\hasni\pymontecarlo\pymontecarlo-casino2\testing-pymontecarlo.py", line 93, in main
    with LocalSimulationRunner(project) as runner:

AttributeError: __enter__

Do you think this is due to an error as a result of the nosetests failing or is it to do with something else? Again, I'm still learning this stuff so any additional help or explanation would be great.

**Comment by hasni4** [comment]
Hi,

Just wanted to follow up on this and see if you know of a solution.

Thanks!

**Comment by ppinard** [comment]
Thank you for the reminder. I forgot to reply to your initial comment. 

Unfortunately, the example is not up-to-date. How to run simulations has changed since this example was written (June 2017). I will try to look at the unit test failures you reported, but in the meantime, maybe the documentation in the branch `jupyter` might help: https://pymontecarlo.readthedocs.io/en/jupyter/tutorials/first-simulation.html#Running-simulation(s).

**Comment by hasni4** [comment]
Hi,

I just wanted to update you. I noticed the newer installation instructions on the guide you suggested and followed it. The pytest for pymontecarlo and casino2 showed no problems at all! However, when running the pytest for pymontecarlo-penepma I got quite a few errors. I’ve attached the failed tests to this post so you could look at them and see what’s wrong.
However when compiling a script to run pymontecarlo-Casino2 based on the instructions from the new documentation, I ran into a SyntaxError due to running ‘await’ outside async function. Here is the code I've used to run a quick test which caused the error:

'
def test(argv=None):

    #PROGRAM SETUP

    from pymontecarlo_casino2.program import Casino2Program
    
    program = Casino2Program(10000)
    
    # program.number_trajectories = 10000
    
    
    #BEAM SETUP
    from pymontecarlo.options.beam import PencilBeam
    
    beam = PencilBeam(15e3)     #default position is 0,0 and energy in eV
    
    # beam.x_m = 100e-9
    # beam.y_m = 100e-9         set up custom beam position 
    
    #SAMPLE SETUP
    
    """
    Therea are 5 different samples:
    substrate using SubstrateSample
    inclusion using InclusionSample 
    horizontal layered using HorizontalLayerSample 
    vertical layered using VericalLayerSample
    sphere using SphereSample
    """
    from  pymontecarlo.options.material import Material
    
    carbon = Material.pure(6)             #Pure carbon
    gold = Material.pure(79)
    """
    SiO2 = Material.from_formula('Si02')   #From formula
    
    composition = {29: 0.4, 30:0.6}
    brass = Material('Brass', composition)  #From composition 
    """
    #material.density_kg_per_m3 = 1000      change mass density
    #material.density_g_per_cm3 = 2.66 
    
    from pymontecarlo.options.sample import VerticalLayerSample
    
    sample = VerticalLayerSample(left_material=carbon, right_material=gold) #making a sample with 3 layers
    """
    sample.add_layer(SiO2, 100e-9)
    sample.add_layer(brass, 50e-9)
    """
    
    import matplotlib.pyplot as plt
    from pymontecarlo.figures.sample import SampleFigure, Perspective
    
    fig, axes = plt.subplots(1, 3, figsize=(10, 3))
    
    samplefig = SampleFigure(sample, beams=[beam])
    
    for ax, perspective in zip(axes, Perspective):
    samplefig.perspective = perspective
    samplefig.draw(ax)
    
    plt.show()
    
    #DETECTOR SETUP
    
    from pymontecarlo.options.detector import PhotonDetector
    import math
    
    detector = PhotonDetector(name = 'detector1', elevation_rad=math.radians(40))
    
    from pymontecarlo.options.analysis import PhotonIntensityAnalysis
    analysis = PhotonIntensityAnalysis(detector)
    
    #PUT TOGETHER OPTIONS
    from pymontecarlo.options import Options
    options = Options(program, beam, sample, [analysis])
    
    #RUN SIM
    from pymontecarlo.runner.helper import run_async
    project = await run_async([options])
    
    import os
    import tempfile
    project.write(os.path.join(tempfile.gettempdir(), 'project1.h5'))
    
    #GET RESULTS
    simulation = project.simulations[0]
    print('Simulation at {}keV contains {} result(s)'.format(simulation.options.beam.energy_keV, len(simulation.results)))
    
    result = simulation.results[0]
    print('Available X-ray intensities:')
    for xrayline in result:
    print(xrayline.siegbahn)
  if __name__ == "__main__":
    test()
'

Could you help with this?

[pymontecarlo-penepma pytests.txt](https://github.com/pymontecarlo/pymontecarlo/files/6640091/pymontecarlo-penepma.pytests.txt)

**Comment by ppinard** [comment]
Hi, I would need to dig a bit more about the failed tests, but you need to declare the function test `async` 
```python
async def test(argv=None):
     ...
```

and run the function using Python's asyncio

```python
if __name__ == "__main__":
     import asyncio
     asyncio.run(test())
```

**Comment by hasni4** [comment]
Thanks for the help! Let me know if you need anything else for the failed tests. 

It might also be worth noting that with Spyder, there is a case where RuntimeErrors occur because of Sypder creating its own event loops. The solutions I used to solve the issue are here: https://stackoverflow.com/questions/56154176/runtimeerror-asyncio-run-cannot-be-called-from-a-running-event-loop/56156310
It might be useful for others as well if they encounter a similar problem.

**Comment by ppinard** [comment]
I updated pymontecarlo, pymontecarlo-casino2, pypenelopetools, and pymontecarlo-penepma and now all the tests are passing (see links to the GitHub Actions in the [README](https://github.com/pymontecarlo/pymontecarlo#build-status)). Please let me know if you still have issues.
