### ISSUE TITLE
Installation problem of pypenelopelib in development mode on windows

### ISSUE THREAD

**Issue by ppinard** [pymontecarlo/pymontecarlo#9]
From @drix00

The package cannot be install because of a compilation error with the following command:

```
#!cmd

py -3 -m pip install -e pypenelopelib
```

The fortran compiler is installed and visible:

```
#!cmd

D:\work\codings\pymontecarlo> gfortran --version
GNU Fortran (GCC) 4.8.3
Copyright (C) 2013 Free Software Foundation, Inc.

GNU Fortran comes with NO WARRANTY, to the extent permitted by law.
You may redistribute copies of GNU Fortran
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING

```

This is on windows 7 64-bit.

The full output:

```
#!txt

D:\work\codings\pymontecarlo> py -3 -m pip install -e pypenelopelib
Obtaining file:///D:/work/codings/pymontecarlo/pypenelopelib
Installing collected packages: pypenelopelib
  Running setup.py develop for pypenelopelib
    Complete output from command C:\Python34\python.exe -c "import setuptools, tokenize; __file__='D:\\work\\codings\\pymontecarlo\\pypenelopelib\\setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps:
    running develop
    running egg_info
    writing pypenelopelib.egg-info\PKG-INFO
    writing top-level names to pypenelopelib.egg-info\top_level.txt
    writing dependency_links to pypenelopelib.egg-info\dependency_links.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pypenelopelib.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pypenelopelib.egg-info\SOURCES.txt'
    running build_ext
    building penelope library
    gfortran -shared -static-libgcc -static-libgfortran -o D:\work\codings\pymontecarlo\pypenelopelib\pypenelopelib\penelope.dll pypenelopelib/penelope.f pypenelopelib/pengeom.f pypenelopelib/penvared.f pypenelopelib/rita.f pypenelopelib/timer.f pypenelopelib/utils.f
    /usr/lib/gcc/x86_64-pc-cygwin/4.8.3/libgfortran.a(read.o): In function `_gfortrani_convert_real':
    /usr/src/debug/gcc-4.8.3-5/libgfortran/io/read.c:155:(.text$_gfortrani_convert_real+0x40): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `strtoflt128'
    /usr/lib/gcc/x86_64-pc-cygwin/4.8.3/libgfortran.a(read.o): In function `_gfortrani_convert_infnan':
    /usr/src/debug/gcc-4.8.3-5/libgfortran/io/read.c:229:(.text$_gfortrani_convert_infnan+0x52): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `strtoflt128'
    /usr/lib/gcc/x86_64-pc-cygwin/4.8.3/libgfortran.a(write.o): In function `write_float':
    /usr/src/debug/gcc-4.8.3-5/libgfortran/io/write_float.def:1272:(.text$write_float+0x1a0): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `quadmath_snprintf'
    /usr/lib/gcc/x86_64-pc-cygwin/4.8.3/libgfortran.a(write.o): In function `determine_en_precision':
    /usr/src/debug/gcc-4.8.3-5/libgfortran/io/write_float.def:1185:(.text$write_float+0x87b): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `quadmath_snprintf'
    /usr/lib/gcc/x86_64-pc-cygwin/4.8.3/libgfortran.a(write.o): In function `write_float':
    /usr/src/debug/gcc-4.8.3-5/libgfortran/io/write_float.def:1272:(.text$write_float+0x8de): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `quadmath_snprintf'
    /usr/lib/gcc/x86_64-pc-cygwin/4.8.3/libgfortran.a(write.o): In function `output_float_FMT_G_16':
    /usr/src/debug/gcc-4.8.3-5/libgfortran/io/write_float.def:1112:(.text$write_float+0xf82): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `quadmath_snprintf'
    /usr/src/debug/gcc-4.8.3-5/libgfortran/io/write_float.def:1112:(.text$write_float+0x1803): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `quadmath_snprintf'
    collect2: error: ld returned 1 exit status
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "D:\work\codings\pymontecarlo\pypenelopelib\setup.py", line 134, in <module>
        cmdclass={'build_ext': build_ext},
      File "C:\Python34\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Python34\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Python34\lib\site-packages\setuptools\command\develop.py", line 32, in run
        self.install_for_development()
      File "C:\Python34\lib\site-packages\setuptools\command\develop.py", line 117, in install_for_development
        self.run_command('build_ext')
      File "C:\Python34\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "D:\work\codings\pymontecarlo\pypenelopelib\setup.py", line 29, in run
        library_dir = self.build_libpenelope()
      File "D:\work\codings\pymontecarlo\pypenelopelib\setup.py", line 75, in build_libpenelope
        subprocess.check_call(args)
      File "C:\Python34\lib\subprocess.py", line 561, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['gfortran', '-shared', '-static-libgcc', '-static-libgfortran', '-o', 'D:\\work\\codings\\pymontecarlo\\pypenelopelib\\pypenelopelib\\penelope.dll', 'pypenelopelib/penelope.f', 'pypenelopelib/pengeom.f', 'pypenelopelib/penvared.f', 'pypenelopelib/rita.f', 'pypenelopelib/timer.f', 'pypenelopelib/utils.f']' returned non-zero exit status 1

    ----------------------------------------
Command "C:\Python34\python.exe -c "import setuptools, tokenize; __file__='D:\\work\\codings\\pymontecarlo\\pypenelopelib\\setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps" failed with error code 1 in D:\work\codings\pymontecarlo\pypenelopelib
```

**Comment by ppinard** [comment]
pypenelopelib is not longer used or supported.
